#
# @package Ultimate SEO URL phpBB SEO
# @version $$
# @copyright (c) 2014 www.phpbb-seo.com
# @license http://opensource.org/licenses/gpl-2.0.php GNU General Public License v2
#
# You must indent with 4 spaces instead of 1 tab
#
services:
    phpbbseo.usu.core:
        class: phpbbseo\usu\core
        arguments:
            - @config
            - @request
            - @user
            - @auth
            - %core.root_path%
            - %core.php_ext%

    phpbbseo.usu.listener:
        class: phpbbseo\usu\event\listener
        arguments:
            - @phpbbseo.usu.core
            - @config
            - @auth
            - @template
            - @user
            - @request
            - @dbal.conn
            - %core.root_path%
            - %core.php_ext%
        tags:
            - { name: event.listener }

    phpbb.usu.pagination:
        class: phpbbseo\usu\pagination
        arguments:
            - @phpbbseo.usu.core
            - @template
            - @user
            - @controller.helper
            - %core.php_ext%
